apiVersion: v2
appVersion: "1.0"
description: A Helm chart for sscs-post-deployment-ft-tests App
name: sscs-post-deployment-ft-tests
home: https://github.com/hmcts/sscs-post-deployment-ft-tests
version: 0.0.3
maintainers:
  - name: HMCTS SSCS team
dependencies:
  - name: java
    version: 5.0.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
